apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello-demo
  ports:
  - port: 80 # what service is listening on, in cluster that is tied to cluster ip, if we're using dns (access via name)
    targetPort: 8080 # match port for application
    nodePort: 31000 # port is usually (30000-32767), accessible from outside of the cluster
