spring:
  datasource:
    url: jdbc:h2:mem:dbtest
    username: sa
    password: pass
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create