spring:
  datasource:
    url: ${DB_URL_JAVALIN}
    username: ${DB_USER}
    password: ${DB_PASS}
# Leveraging environment variables
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      # ddl-auto refers to how hibernate should handle ddl, ie: create means to create tables in the database, validate only checks that the schema matches the one defines by the entities