spring:
  datasource:
    url: ${DB_URL_JAVALIN}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      # ddl-auto: create #allows us to create schema in our postgres container db