version: "3.8"

services:
  logging-demo:
    build: .
    ports:
      - 8081:8080
    environment:
      - DB_URL_JAVALIN=jdbc:postgresql://postgres:5432/postgres
      - DB_USER=postgres
      - DB_PASS=pass
    container_name: logging-container
    depends_on:
      - postgres
    volumes:
      - ../logs/application.log:/logs/application.log

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
    container_name: postgres-container
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local