global:
  scrape_interval:     15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - prometheus:9090
  - job_name: logging-demo
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - host.docker.internal:8081