global:
  scrape_interval:     15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
      #alert manager

rule_files:
  - rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - prometheus:9090
  - job_name: logging-demo
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - host.docker.internal:8081