version: "3.8"
services:
  promtail:
    image: grafana/promtail:latest
    container_name: logging-promtail
    volumes:
      - ./promtail/promtail-docker-config.yml:/etc/promtail/docker-config.yaml
      - ../logs/application.log:/var/log/application.log
    command: "--config.file=/etc/promtail/docker-config.yaml"
  loki:
    image: grafana/loki:latest
    container_name: logging-loki
    ports:
      - 3100:3100
  grafana:
    image: grafana/grafana:latest
    container_name: logging-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    # persisting grafana settings
    ports:
      - 3000:3000
    depends_on:
      - loki
volumes:
  grafana-data:
    driver: local